backend:
  name: git-gateway
  branch: admin   # Change if your repo uses another branch

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "site_settings.json"
        label: "Donation Settings"
        name: "settings"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
